"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25

Creates every table in docs/DATABASE_SCHEMA.md. Written by hand against
backend/app/models/models.py rather than autogenerated, so it's readable as
the canonical "first migration" for a fresh database.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')  # gen_random_uuid()

    op.create_table(
        "users",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("auth_uid", sa.String, nullable=False, unique=True),
        sa.Column("email", sa.String, nullable=False, unique=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("role", sa.Enum("admin", "participant", name="role"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "admins",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("permissions", pg.JSONB, server_default="{}"),
    )

    op.create_table(
        "participants",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("participant_code", sa.String, nullable=False, unique=True),
        sa.Column("department", sa.String),
        sa.Column("year", sa.Integer),
        sa.Column("phone", sa.String),
        sa.Column("registered_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "competitions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String, nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "draft", "registration_open", "registration_closed", "round1_active", "round1_closed",
                "qualification_done", "teams_created", "round2_active", "round2_closed", "finalized",
                name="competition_state",
            ),
            nullable=False,
            server_default="draft",
        ),
        sa.Column("round1_duration_seconds", sa.Integer, nullable=False),
        sa.Column("round2_team_duration_seconds", sa.Integer, nullable=False),
        sa.Column("round2_early_handoff_allowed", sa.Boolean, server_default=sa.true()),
        sa.Column("registration_open", sa.Boolean, server_default=sa.false()),
        sa.Column("created_by", pg.UUID(as_uuid=True), sa.ForeignKey("admins.id")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True)),
    )

    op.create_table(
        "questions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("competition_id", pg.UUID(as_uuid=True), sa.ForeignKey("competitions.id"), nullable=False),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("option_a", sa.Text, nullable=False),
        sa.Column("option_b", sa.Text, nullable=False),
        sa.Column("option_c", sa.Text, nullable=False),
        sa.Column("option_d", sa.Text, nullable=False),
        sa.Column("correct_option", sa.Enum("A", "B", "C", "D", name="option_label"), nullable=False),
        sa.Column("category", sa.String),
        sa.Column("difficulty", sa.Enum("easy", "medium", "hard", name="difficulty"), server_default="medium"),
        sa.Column("marks", sa.Integer, server_default="1"),
        sa.Column("is_enabled", sa.Boolean, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "quiz_attempts",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("participant_id", pg.UUID(as_uuid=True), sa.ForeignKey("participants.id"), nullable=False),
        sa.Column("competition_id", pg.UUID(as_uuid=True), sa.ForeignKey("competitions.id"), nullable=False),
        sa.Column("question_order", pg.JSONB, nullable=False),
        sa.Column("option_order", pg.JSONB, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True)),
        sa.Column(
            "status",
            sa.Enum("in_progress", "submitted", "auto_submitted", name="attempt_status"),
            server_default="in_progress",
        ),
        sa.Column("score", sa.Integer),
        sa.Column("correct_count", sa.Integer),
        sa.Column("incorrect_count", sa.Integer),
        sa.Column(
            "qualification_status",
            sa.Enum("pending", "qualified", "not_qualified", name="qualification_status"),
            server_default="pending",
        ),
        sa.UniqueConstraint("participant_id", "competition_id"),
    )

    op.create_table(
        "quiz_answers",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("attempt_id", pg.UUID(as_uuid=True), sa.ForeignKey("quiz_attempts.id"), nullable=False),
        sa.Column("question_id", pg.UUID(as_uuid=True), sa.ForeignKey("questions.id"), nullable=False),
        sa.Column("selected_option", sa.Enum("A", "B", "C", "D", name="option_label", create_type=False)),
        sa.Column("is_correct", sa.Boolean),
        sa.Column("answered_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "teams",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("competition_id", pg.UUID(as_uuid=True), sa.ForeignKey("competitions.id"), nullable=False),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("color", sa.String),
        sa.Column("icon", sa.String),
        sa.Column(
            "status", sa.Enum("pending", "active", "paused", "completed", name="team_status"),
            server_default="pending",
        ),
        sa.Column("round2_access", sa.Boolean, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "team_members",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("team_id", pg.UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("participant_id", pg.UUID(as_uuid=True), sa.ForeignKey("participants.id"), nullable=False),
        sa.Column("member_number", sa.Integer, nullable=False),
        sa.UniqueConstraint("team_id", "member_number"),
        sa.UniqueConstraint("team_id", "participant_id"),
    )

    op.create_table(
        "team_sessions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("team_id", pg.UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False, unique=True),
        sa.Column("team_started_at", sa.DateTime(timezone=True)),
        sa.Column("team_deadline", sa.DateTime(timezone=True)),
        sa.Column("current_member_number", sa.Integer),
        sa.Column("member_started_at", sa.DateTime(timezone=True)),
        sa.Column("member_deadline", sa.DateTime(timezone=True)),
        sa.Column(
            "status",
            sa.Enum("not_started", "active", "completed", "expired", name="session_status"),
            server_default="not_started",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "coding_problems",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("competition_id", pg.UUID(as_uuid=True), sa.ForeignKey("competitions.id"), nullable=False),
        sa.Column("title", sa.String, nullable=False),
        sa.Column("statement_md", sa.Text, nullable=False),
        sa.Column("constraints_md", sa.Text),
        sa.Column("position", sa.Integer, nullable=False),
        sa.Column("max_score", sa.Integer, server_default="100"),
        sa.Column("time_limit_ms", sa.Integer, server_default="2000"),
        sa.Column("memory_limit_mb", sa.Integer, server_default="256"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "test_cases",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("problem_id", pg.UUID(as_uuid=True), sa.ForeignKey("coding_problems.id"), nullable=False),
        sa.Column("input", sa.Text, nullable=False),
        sa.Column("expected_output", sa.Text, nullable=False),
        sa.Column("is_sample", sa.Boolean, server_default=sa.false()),
        sa.Column("weight", sa.Integer, server_default="1"),
    )

    op.create_table(
        "code_drafts",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("team_id", pg.UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("problem_id", pg.UUID(as_uuid=True), sa.ForeignKey("coding_problems.id"), nullable=False),
        sa.Column("language", sa.String, nullable=False),
        sa.Column("source_code", sa.Text, server_default=""),
        sa.Column("last_edited_by", pg.UUID(as_uuid=True), sa.ForeignKey("team_members.id")),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.UniqueConstraint("team_id", "problem_id"),
    )

    op.create_table(
        "submissions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("team_id", pg.UUID(as_uuid=True), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("problem_id", pg.UUID(as_uuid=True), sa.ForeignKey("coding_problems.id"), nullable=False),
        sa.Column("member_id", pg.UUID(as_uuid=True), sa.ForeignKey("team_members.id"), nullable=False),
        sa.Column("language", sa.String, nullable=False),
        sa.Column("source_code", sa.Text, nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "accepted", "wrong_answer", "compilation_error", "runtime_error", "tle", "mle",
                name="submission_status",
            ),
            nullable=False,
        ),
        sa.Column("execution_time_ms", sa.Integer),
        sa.Column("memory_kb", sa.Integer),
        sa.Column("score", sa.Integer, server_default="0"),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "leaderboards",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("competition_id", pg.UUID(as_uuid=True), sa.ForeignKey("competitions.id"), nullable=False),
        sa.Column("round_number", sa.Integer, nullable=False),
        sa.Column("subject_type", sa.String, nullable=False),
        sa.Column("subject_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("score", sa.Integer, nullable=False),
        sa.Column("tiebreak_time_seconds", sa.Integer, nullable=False),
        sa.Column("rank", sa.Integer, nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id")),
        sa.Column("action", sa.String, nullable=False),
        sa.Column("metadata", pg.JSONB, server_default="{}"),
        sa.Column("ip_address", sa.String),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_index("ix_quiz_answers_attempt_id", "quiz_answers", ["attempt_id"])
    op.create_index("ix_team_members_participant_id", "team_members", ["participant_id"])
    op.create_index("ix_code_drafts_team_id", "code_drafts", ["team_id"])
    op.create_index("ix_submissions_team_id", "submissions", ["team_id"])
    op.create_index("ix_leaderboards_competition_round", "leaderboards", ["competition_id", "round_number"])


def downgrade() -> None:
    op.drop_table("audit_logs")
    op.drop_table("leaderboards")
    op.drop_table("submissions")
    op.drop_table("code_drafts")
    op.drop_table("test_cases")
    op.drop_table("coding_problems")
    op.drop_table("team_sessions")
    op.drop_table("team_members")
    op.drop_table("teams")
    op.drop_table("quiz_answers")
    op.drop_table("quiz_attempts")
    op.drop_table("questions")
    op.drop_table("competitions")
    op.drop_table("participants")
    op.drop_table("admins")
    op.drop_table("users")

    for enum_name in (
        "role", "competition_state", "option_label", "difficulty", "attempt_status",
        "qualification_status", "team_status", "session_status", "submission_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
